[package]
name = "xelis_wallet_flutter"
version = "0.3.0"
edition = "2021"
description = "Native XELIS wallet runtime bindings for Flutter."
license = "GPL-3.0-only"
readme = "../README.md"
publish = false

[lib]
name = "xelis_wallet_flutter"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.13.0", features = ["log"] }
anyhow = "1"
futures = "0.3"
indexmap = { version = "2.0.0", features = ["serde"] }
log = "0.4"
parking_lot = "0.12.1"
lazy_static = "1.4.0"
serde_json = "1"
xelis_wallet = { git = "https://github.com/xelis-project/xelis-blockchain", rev = "b149b57aaeec42a27b0e1516a2e8ed8e00c6f394", package = "xelis_wallet", default-features = false, features = ["network_handler"] }
xelis_common = { git = "https://github.com/xelis-project/xelis-blockchain", rev = "b149b57aaeec42a27b0e1516a2e8ed8e00c6f394", package = "xelis_common" }
serde = { version = "1.0.197", features = ["derive"] }
trie-rs = "0.4.2"
regex = "1.11.1"
url = "2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rustls = { version = "*", features = ["ring"], default-features = false }
tempfile = "3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.92"
getrandom = { version = "0.3", features = ["wasm_js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = ["api_server"]
api_server = ["xelis_wallet/api_server", "network_handler", "xswd"]
network_handler = ["xelis_wallet/network_handler"]
xswd = ["xelis_wallet/xswd"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
